CREATE TABLE customer_credential
(
    credential_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password_hash    VARCHAR(255) NOT NULL,
    email_verified   BOOLEAN      NOT NULL,
    account_owner_id BIGINT       NOT NULL,

    CONSTRAINT uq_customer_credential_account_owner
        UNIQUE (account_owner_id),

    CONSTRAINT fk_customer_credential_account_owner
        FOREIGN KEY (account_owner_id)
            REFERENCES account_owner (account_owner_id)


)